package com.liuyang19900520.iotmobile_android.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.liuyang19900520.iotmobile_android.model.bean.TestApiBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_API_BEAN".
*/
public class TestApiBeanDao extends AbstractDao<TestApiBean, Long> {

    public static final String TABLENAME = "TEST_API_BEAN";

    /**
     * Properties of entity TestApiBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Category = new Property(1, String.class, "category", false, "CATEGORY");
        public final static Property ApiName = new Property(2, String.class, "apiName", false, "API_NAME");
        public final static Property ApiUrl = new Property(3, String.class, "apiUrl", false, "API_URL");
        public final static Property Params = new Property(4, String.class, "params", false, "PARAMS");
        public final static Property CreatedAt = new Property(5, java.util.Date.class, "createdAt", false, "created_at");
        public final static Property UpdatedAt = new Property(6, java.util.Date.class, "updatedAt", false, "updated_at");
    }


    public TestApiBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TestApiBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_API_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CATEGORY\" TEXT," + // 1: category
                "\"API_NAME\" TEXT," + // 2: apiName
                "\"API_URL\" TEXT," + // 3: apiUrl
                "\"PARAMS\" TEXT," + // 4: params
                "\"created_at\" INTEGER NOT NULL ," + // 5: createdAt
                "\"updated_at\" INTEGER NOT NULL );"); // 6: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_API_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestApiBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(2, category);
        }
 
        String apiName = entity.getApiName();
        if (apiName != null) {
            stmt.bindString(3, apiName);
        }
 
        String apiUrl = entity.getApiUrl();
        if (apiUrl != null) {
            stmt.bindString(4, apiUrl);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(5, params);
        }
        stmt.bindLong(6, entity.getCreatedAt().getTime());
        stmt.bindLong(7, entity.getUpdatedAt().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestApiBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(2, category);
        }
 
        String apiName = entity.getApiName();
        if (apiName != null) {
            stmt.bindString(3, apiName);
        }
 
        String apiUrl = entity.getApiUrl();
        if (apiUrl != null) {
            stmt.bindString(4, apiUrl);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(5, params);
        }
        stmt.bindLong(6, entity.getCreatedAt().getTime());
        stmt.bindLong(7, entity.getUpdatedAt().getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestApiBean readEntity(Cursor cursor, int offset) {
        TestApiBean entity = new TestApiBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // category
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // apiName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // apiUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // params
            new java.util.Date(cursor.getLong(offset + 5)), // createdAt
            new java.util.Date(cursor.getLong(offset + 6)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestApiBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategory(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setApiName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setApiUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParams(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreatedAt(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUpdatedAt(new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestApiBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestApiBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestApiBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
